services:
  postgres:
    user: ${UID:-1000}:${GID:-1000}
    image: postgres:18
    env_file:
      - services/database/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql:rw
    restart: unless-stopped
    networks:
      - postgres
  api:
    build:
      context: services/api
    env_file:
      - services/database/.env
    environment:
      PORT: ${PORT:-80}
      POSTGRES_HOST: postgres
      STORAGE_POOL_PATH: /app/data/storage/pool
      ENVIRONMENT: ${ENVIRONMENT:-development}
      BASE_URL: http://${DOMAIN:-127.0.0.1}:${PORT:-8080}
      WWW_URL: http://${DOMAIN:-127.0.0.1}:${PORT:-8080}
    volumes:
      - ./data/api:/app/data:rw
    depends_on:
      postgres:
        condition: service_started
        required: true
        restart: true
    restart: unless-stopped
    networks:
      - ingress
      - postgres
  www:
    build:
      context: services/www
    volumes:
      - ./services/www/src:/www:ro
    networks:
      - ingress
  ingress:
    image: nginx:stable-alpine3.23-perl
    volumes:
      - ./services/ingress/nginx:/etc/nginx/conf.d:ro
    ports:
      - 127.0.0.1:${PORT:-8080}:80
    restart: unless-stopped
    networks:
      - ingress

networks:
  ingress:
  postgres:
