services:
  postgres:
    user: ${UID:-1000}:${GID:-1000}
    image: postgres:18
    env_file:
      - services/database/.env
    volumes:
      - ./data/postgres:/var/lib/postgresql:rw
    networks:
      - postgres
  api:
    build:
      context: services/api
    env_file:
      - services/database/.env
    environment:
      PORT: ${PORT:-80}
      POSTGRES_HOST: postgres
      STORAGE_POOL_PATH: /app/data/storage/pool
      ENVIRONMENT: ${ENVIRONMENT:-development}
      BASE_URL: http://${DOMAIN:-127.0.0.1}:${PORT:-8080}
      WWW_URL: http://${DOMAIN:-127.0.0.1}:${PORT:-8080}
    volumes:
      - ./data/api:/app/data:rw
    networks:
      - ingress
      - postgres
  www:
    build:
      context: services/www
    volumes:
      - ./services/www/src:/www:ro
    networks:
      - ingress
  ingress:
    image: nginx:stable-alpine3.23-perl
    volumes:
      - ./services/ingress/nginx:/etc/nginx/conf.d:ro
    ports:
      - 127.0.0.1:${PORT:-8080}:80
    networks:
      - ingress
  pgadmin:
    image: elestio/pgadmin:REL-9_12
    environment:
      PGADMIN_DEFAULT_EMAIL: e@m.c
      PGADMIN_DEFAULT_PASSWORD: emc
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "127.0.0.1:${PGADMIN_PORT:-8081}:8080"
    volumes:
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - postgres
    profiles: [debug]

networks:
  ingress:
  postgres:
