services:
  pgadmin:
    image: elestio/pgadmin:REL-9_12
    environment:
      PGADMIN_DEFAULT_EMAIL: e@m.c
      PGADMIN_DEFAULT_PASSWORD: emc
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "127.0.0.1:8081:8080"
    volumes:
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - postgres

networks:
  postgres:
    external: true
