# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/spec.openapis.org/refs/heads/main/oas/3.1/schema/2025-11-23
openapi: 3.1.0

info:
  title: Authentication API
  contact:
    url: https://t.me/energostalin
    name: EnergoStalin
    email: ens.stalin@gmail.com
  license:
    name: GPLv3
  version: 1.0.0

servers:
  - url: http://127.0.0.1:7727
    description: Local development server

components:
  schemas:
    ValidationRule:
      type: object
      properties:
        regex:
          type: string
          example: "^[a-zA-Z0-9]{3,20}$"
        description:
          type: string
          example: "3-20"
      required:
        - regex
        - description
    UserAuth:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          example: EnergoStalin
        password:
          type: string
          example: PassW0RT
    AuthConfig:
      type: object
      required:
        - validation
      properties:
        validation:
          type: object
          required:
            - login
            - password
          properties:
            login:
              $ref: '#/components/schemas/ValidationRule'
            password:
              $ref: '#/components/schemas/ValidationRule'

  responses:
    JWTResponse:
      description: ""
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: string
              refreshToken:
                type: string
              expiresAt:
                type: string
                format: date-time
    AuthValidationConfigResponse:
      description: ""
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthConfig'
    UserValidationConfigResponse:
      description: ""
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EditUserConfig'
    ErrorResponse:
      description: ""
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

  requestBodies:
    UserAuth:
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/UserAuth'

  securitySchemes:
    token:
      type: apiKey
      name: token
      scheme: bearer
      bearerFormat: JWT
      in: cookie

paths:
  /health:
    $ref: 'common.yaml#/components/pathItems/health'
  /auth:
    description: Создаёт нового пользователя или авторизует существующего
    post:
      requestBody:
        $ref: '#/components/requestBodies/UserAuth'
      responses:
        '200':
          $ref: '#/components/responses/JWTResponse'
  /auth/refresh:
    description: Выдаёт новый JWT в обмен на рефреш токен
    post:
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: 'Пример рефреш токена'
      responses:
        '200':
          $ref: '#/components/responses/JWTResponse'
  /auth/config:
    get:
      responses:
        '200':
          $ref: '#/components/responses/AuthValidationConfigResponse'
