# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/spec.openapis.org/refs/heads/main/oas/3.1/schema/2025-11-23
openapi: 3.1.0

info:
  title: Common API
  contact:
    url: https://t.me/energostalin
    name: EnergoStalin
    email: ens.stalin@gmail.com
  license:
    name: WTFNMFPL
    identifier: WTFNMFPL
  version: 1.0.0

components:
  schemas:
    HealthResponse:
      type: string
      example: OK
    GenericError:
      type: object
      properties:
        error:
          type: string

  responses:
    HealthResponse:
      description: ""
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/HealthResponse'
    GenericError:
      description: ""
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericError'

  pathItems:
    health:
      get:
        responses:
          '200':
            $ref: '#/components/responses/HealthResponse'
