# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/spec.openapis.org/refs/heads/main/oas/3.1/schema/2025-11-23
openapi: 3.1.0

info:
  title: Storage API
  contact:
    url: https://t.me/energostalin
    name: EnergoStalin
    email: ens.stalin@gmail.com
  license:
    name: GPLv3
  version: 1.0.0

servers:
  - url: http://127.0.0.1:7729
    description: Local development server

components:
  schemas:
    LogEntry:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        level:
          type: integer
          minimum: 0
        service:
          type: string
        message:
          type: string

paths:
  /journal:
    post:
      requestBody:
        content:
          application/jsonl:
            schema:
              $ref: '#/components/schemas/LogEntry'
      responses:
        '200':
          description: ""
